language: python

services:
  - docker

before_install:
  - docker build -t bravado_django_test_client:${TRAVIS_COMMIT} -f Dockerfile.test .

script:
   - docker run bravado_django_test_client:${TRAVIS_COMMIT}
